### PR TITLE
Patch

### PR DESCRIPTION
**Pull request by genych**
Hey!

You asked how to deploy it on heroku? (https://www.reddit.com/r/learnpython/comments/4a0shj/web_app_works_locally_but_gets_error_on_heroku/)

Have a quick fix. Looks like it works: https://somethingwithfood.herokuapp.com/ (I'll remove it after)

### CODE REVIEW

**Comment by montrealks** [comment]
Oh man, thats really incredibly. I knew I was close but I didn't think I
was that close. Thank you so very much. Its embarrassing but I actually
spent 2 days trying to figure it out! Thanks again!!!

**Comment by montrealks** [comment]
https://dataminerfood.herokuapp.com/

There I got it hosted. I am actually so thrilled. Thanks again.

**Comment by genych** [comment]
Grand! You are welcome. I'm new to heroku as well, so it was interesting challenge to dig this trouble

**Comment by montrealks** [comment]
So now that my app is running, and it is getting code from GitHub, does
that mean that whenever I do a git commit from my command prompt that those
changes will make their way automatically into the live app?

**Comment by genych** [comment]
Heroku have 'github integration' feature. But it should be enabled and configured manually for auto-deploy. That's all I know.

**Pull request merged**
